# Generated by Django 3.2.6 on 2021-08-28 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='created',
            new_name='Created',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='updated',
            new_name='Updated',
        ),
    ]
